### ISSUE TITLE
Build fails: `error: no matching function for call to 'Kst::DataMatrix::saveFilename(QCoreXmlStreamWriter&)'`

### ISSUE THREAD

**Issue by barracuda156** [Kst-plot/kst#24]
Same error with 2.0.8 and 2.1, with gcc-4.2 and gcc14.

```
[  6%] Building CXX object src/libkst/CMakeFiles/kst2core.dir/datasource.cpp.o
cd /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/build/src/libkst && /opt/local/bin/ccache /opt/local/bin/g++-mp-14 -DBUILD_KSTCORE -DKST_HAVE_REVISION_H -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -Dkst2core_EXPORTS -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/build -I/opt/local/libexec/qt4/include/QtDesigner -I/opt/local/libexec/qt4/lib/QtAssistant.framework/Headers -I/opt/local/libexec/qt4/include/QtDeclarative -I/opt/local/libexec/qt4/include/QtScriptTools -I/opt/local/libexec/qt4/include/QtDBus -I/opt/local/libexec/qt4/include/QtXml -I/opt/local/libexec/qt4/include/QtSql -I/opt/local/libexec/qt4/include/QtOpenGL -I/opt/local/libexec/qt4/include/QtMultimedia -I/opt/local/libexec/qt4/include/QtNetwork -I/opt/local/libexec/qt4/include/QtXmlPatterns -I/opt/local/libexec/qt4/include/QtWebKit -I/opt/local/libexec/qt4/include/QtHelp -I/opt/local/libexec/qt4/include/QtUiTools -I/opt/local/libexec/qt4/include/QtTest -I/opt/local/libexec/qt4/include/QtScript -I/opt/local/libexec/qt4/include/QtSvg -I/opt/local/libexec/qt4/include/Qt3Support -I/opt/local/libexec/qt4/share/mkspecs/default -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/build/src/libkst -isystem /opt/local/libexec/qt4/include -isystem /opt/local/libexec/qt4/include/QtGui -isystem /opt/local/libexec/qt4/include/QtCore -pipe -Os -DNDEBUG -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -Wall -O3 -DNDEBUG -DQT_NO_WARNING_OUTPUT -arch ppc -mmacosx-version-min=10.6 -fPIC -MD -MT src/libkst/CMakeFiles/kst2core.dir/datasource.cpp.o -MF CMakeFiles/kst2core.dir/datasource.cpp.o.d -o CMakeFiles/kst2core.dir/datasource.cpp.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datasource.cpp
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datamatrix.cpp: In member function 'virtual void Kst::DataMatrix::save(QCoreXmlStreamWriter&)':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datamatrix.cpp:66:17: error: no matching function for call to 'Kst::DataMatrix::saveFilename(QCoreXmlStreamWriter&)'
   66 |     saveFilename(xml);
      |     ~~~~~~~~~~~~^~~~~
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datamatrix.h:19,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datamatrix.cpp:15:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:48:10: note: candidate: 'void Kst::DataPrimitive::saveFilename(QXmlStreamWriter&)'
   48 |     void saveFilename(QXmlStreamWriter&);
      |          ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:48:23: note:   no known conversion for argument 1 from 'QCoreXmlStreamWriter' to 'QXmlStreamWriter&'
   48 |     void saveFilename(QXmlStreamWriter&);
      |                       ^~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:49:17: note: candidate: 'static void Kst::DataPrimitive::saveFilename(const QString&, QXmlStreamWriter&)'
   49 |     static void saveFilename(const QString&, QXmlStreamWriter&);
      |                 ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:49:17: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [src/libkst/CMakeFiles/kst2core.dir/datamatrix.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.cpp:99:6: error: no declaration matches 'void Kst::DataPrimitive::saveFilename(QCoreXmlStreamWriter&)'
   99 | void DataPrimitive::saveFilename(QXmlStreamWriter& s) {
      |      ^~~~~~~~~~~~~
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.cpp:18:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:49:17: note: candidates are: 'static void Kst::DataPrimitive::saveFilename(const QString&, QXmlStreamWriter&)'
   49 |     static void saveFilename(const QString&, QXmlStreamWriter&);
      |                 ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:48:10: note:                 'void Kst::DataPrimitive::saveFilename(QXmlStreamWriter&)'
   48 |     void saveFilename(QXmlStreamWriter&);
      |          ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:39:22: note: 'class Kst::DataPrimitive' defined here
   39 | class KSTCORE_EXPORT DataPrimitive
      |                      ^~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.cpp:108:6: error: no declaration matches 'void Kst::DataPrimitive::saveFilename(const QString&, QCoreXmlStreamWriter&)'
  108 | void DataPrimitive::saveFilename(const QString& fileName, QXmlStreamWriter& s)
      |      ^~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:49:17: note: candidates are: 'static void Kst::DataPrimitive::saveFilename(const QString&, QXmlStreamWriter&)'
   49 |     static void saveFilename(const QString&, QXmlStreamWriter&);
      |                 ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:48:10: note:                 'void Kst::DataPrimitive::saveFilename(QXmlStreamWriter&)'
   48 |     void saveFilename(QXmlStreamWriter&);
      |          ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:39:22: note: 'class Kst::DataPrimitive' defined here
   39 | class KSTCORE_EXPORT DataPrimitive
      |                      ^~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.cpp:114:9: error: no declaration matches 'QString Kst::DataPrimitive::readFilename(const QCoreXmlStreamAttributes&)'
  114 | QString DataPrimitive::readFilename(const QXmlStreamAttributes& attrs)
      |         ^~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:51:20: note: candidate is: 'static QString Kst::DataPrimitive::readFilename(const QXmlStreamAttributes&)'
   51 |     static QString readFilename(const QXmlStreamAttributes&);
      |                    ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:39:22: note: 'class Kst::DataPrimitive' defined here
   39 | class KSTCORE_EXPORT DataPrimitive
      |                      ^~~~~~~~~~~~~
make[2]: *** [src/libkst/CMakeFiles/kst2core.dir/dataprimitive.cpp.o] Error 1
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datascalar.cpp: In member function 'virtual void Kst::DataScalar::save(QCoreXmlStreamWriter&)':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datascalar.cpp:108:17: error: no matching function for call to 'Kst::DataScalar::saveFilename(QCoreXmlStreamWriter&)'
  108 |     saveFilename(s);
      |     ~~~~~~~~~~~~^~~
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datascalar.h:22,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datascalar.cpp:17:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:48:10: note: candidate: 'void Kst::DataPrimitive::saveFilename(QXmlStreamWriter&)'
   48 |     void saveFilename(QXmlStreamWriter&);
      |          ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:48:23: note:   no known conversion for argument 1 from 'QCoreXmlStreamWriter' to 'QXmlStreamWriter&'
   48 |     void saveFilename(QXmlStreamWriter&);
      |                       ^~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:49:17: note: candidate: 'static void Kst::DataPrimitive::saveFilename(const QString&, QXmlStreamWriter&)'
   49 |     static void saveFilename(const QString&, QXmlStreamWriter&);
      |                 ^~~~~~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/dataprimitive.h:49:17: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [src/libkst/CMakeFiles/kst2core.dir/datascalar.cpp.o] Error 1
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datasource.cpp:42:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/updatemanager.h:51:5: error: 'QElapsedTimer' does not name a type; did you mean 'QBasicTimer'?
   51 |     QElapsedTimer _time;
      |     ^~~~~~~~~~~~~
      |     QBasicTimer
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datasource.cpp: In member function 'QMap<QString, QString> Kst::DataSource::fileMetas() const':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/kst-2.1/src/libkst/datasource.cpp:185:31: error: 'class QFileInfo' has no member named 'birthTime'
  185 |   map["File creation"] = info.birthTime().toString(Qt::ISODate).replace('T', ' ');
      |                               ^~~~~~~~~
make[2]: *** [src/libkst/CMakeFiles/kst2core.dir/datasource.cpp.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/build'
make[1]: *** [src/libkst/CMakeFiles/kst2core.dir/all] Error 2
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_kst/kst/work/build'
make: *** [all] Error 2
```

**Comment by barracuda156** [comment]
```
datasource.cpp:185:31: error: 'class QFileInfo' has no member named 'birthTime'
updatemanager.h:51:5: error: 'QElapsedTimer' does not name a type; did you mean 'QBasicTimer'?
```
These bugs were introduced by https://github.com/Kst-plot/kst/commit/aea52b365bbcf210e774240357e7776e69abd7e3

**Comment by barracuda156** [comment]
I wonder if the first breakage was caused by https://github.com/Kst-plot/kst/commit/ff949c48000b807655eeb5a23d428764d09c84a8
